
















  










  
    
  
  





  
  


document.write("<link rel='stylesheet' type='text/css' href='http://css.gome.com.cn/css/n/firstPage/h_b_c.min.___1352967334000.css'/>");document.write("<link rel='stylesheet' type='text/css' href='http://css.gome.com.cn/css/n/firstPage/main-index-only.min.___1352967334000.css'/>");var _gd={'_zw':'','app':'http://app.gome.com.cn','js':'http://js.gome.com.cn'};(function(b){b._gomeJsConfig=b._gomeJsConfig||{};var a=function(d,e,c){loadOver=function(g,f){var h=g._g_js=g._g_js||[];h.push(f);if(g.readyState){g.onreadystatechange=function(){if(g.readyState=="loaded"||g.readyState=="complete"){g.onreadystatechange=null;for(var j=0;j<h.length;j++){if(h[j]){h[j]();}}h=[];}};}else{g.onload=function(){for(var j=0;j<h.length;j++){if(h[j]){h[j]();}}h=[];};}},loadJs=function(h,f,i){if(!i){var g=document.createElement("script");g.type="text/javascript";g.src=h;document.getElementsByTagName("head")[0].appendChild(g);loadOver(g,f);return g;}else{document.write("<script type='text/javascript' src='"+h+"'><\/script>");if(f){f();}return null;}};if(_gomeJsConfig[d]&&!_gomeJsConfig[d][1]){_gomeJsConfig[d][1]=loadJs(_gomeJsConfig[d][0],function(){_gomeJsConfig[d][1]=2;if(e){e();}},c);}else{if(typeof _gomeJsConfig[d][1]=="object"){loadOver(_gomeJsConfig[d][1],e);}else{if(_gomeJsConfig[d][1]==2){e();}}}};a.addConfig=function(d,e){var c=_gomeJsConfig[d];_gomeJsConfig[d]=c?c:[e];};b.g$=b.g$||a;})(window);(function(_g){g$.addConfig('ginputfocus',_gd['js']+'/js/n/firstPage/ginputfocus.min.___1352967334000.js');g$.addConfig('gclickshow',_gd['js']+'/js/n/firstPage/gclickshow.min.___1352967334000.js');g$.addConfig('jqueryM',_gd['js']+'/js/g/jquery/jqueryM.min.___1352967334000.js');g$.addConfig('overflowauto',_gd['js']+'/js/n/firstPage/overflowauto.min.___1352967334000.js');g$.addConfig('adslide',_gd['js']+'/js/n/firstPage/adslide.min.___1352967334000.js');g$.addConfig('signtop',_gd['js']+'/js/n/firstPage/signtop.min.___1352967334000.js');g$.addConfig('gQgjs',_gd['js']+'/js/n/firstPage/gXsqg.min.___1352967334000.js');g$.addConfig('firstOther',_gd['js']+'/js/n/firstOther.min.___1352967334000.js');g$.addConfig('gtabs',_gd['js']+'/js/g/ui/gtabs.min.___1352967334000.js');g$.addConfig('gomecart',_gd['js']+'/js/n/firstPage/gcart.min.___1352967334000.js');g$.addConfig('cookie',_gd['js']+'/js/g/jquery/jquery.cookie.min.___1352967334000.js');g$.addConfig('searchN',_gd['js']+'/js/n/firstPage/searchN.min.___1352967334000.js');g$.addConfig('headN',_gd['js']+'/js/n/firstPage/headN.min.___1352967334000.js');g$.addConfig('floors',_gd['js']+'/js/n/firstPage/floors.min.___1352967334000.js');g$.addConfig('ghover',_gd['js']+'/js/n/firstPage/ghover.min.___1352967334000.js');g$.addConfig('gomeAutopoint',_gd['js']+'/js/n/firstPage/searchAutoPoint.min.___1352967334000.js');g$.addConfig('scode',_gd['js']+'/js/gz/adobe/s_code-gz.min.___1352967334000.js');g$.addConfig('gRoll',_gd['js']+'/js/g/ui/gRoll.min.___1352967334000.js');g$.addConfig('greplaceimg',_gd['js']+'/js/n/firstPage/greplaceimg.min.___1352967334000.js');g$.addConfig('media',_gd['js']+'/js/n/firstPage/media.min.___1352967334000.js');g$.addConfig('gLoad',_gd['js']+'/js/g/unit/gLoad.min.___1352967334000.js');g$.addConfig('glaterimg',_gd['js']+'/js/n/firstPage/glaterimg.min.___1352967334000.js');})(_gomeJsConfig);