package com.model;

/**
 * TAdmin generated by MyEclipse Persistence Tools
 */

public class TWenan implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	// Fields
	private Integer wenanId;
	private String wenanDesc;
	private String wenanPic;
	private int wenanType;
	private String wenanTime;
	
	public TWenan(){
		
	}

	public TWenan(Integer wenanId, String wenanDesc, String wenanPic, int wenanType, String wenanTime) {
		super();
		this.wenanId = wenanId;
		this.wenanDesc = wenanDesc;
		this.wenanPic = wenanPic;
		this.wenanType = wenanType;
		this.wenanTime = wenanTime;
	}

	public Integer getWenanId() {
		return wenanId;
	}

	public void setWenanId(Integer wenanId) {
		this.wenanId = wenanId;
	}

	public String getWenanDesc() {
		return wenanDesc;
	}

	public void setWenanDesc(String wenanDesc) {
		this.wenanDesc = wenanDesc;
	}

	public String getWenanPic() {
		return wenanPic;
	}

	public void setWenanPic(String wenanPic) {
		this.wenanPic = wenanPic;
	}

	public int getWenanType() {
		return wenanType;
	}

	public void setWenanType(int wenanType) {
		this.wenanType = wenanType;
	}

	public String getWenanTime() {
		return wenanTime;
	}

	public void setWenanTime(String wenanTime) {
		this.wenanTime = wenanTime;
	}

	@Override
	public String toString() {
		return "TWenan [wenanId=" + wenanId + ", wenanDesc=" + wenanDesc + ", wenanPic=" + wenanPic + ", wenanType=" + wenanType
				+ ", wenanTime=" + wenanTime + "]";
	}
	
}